# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd902edde229fc930cc40b9cc9464574ad7aa7e97c2b79bd87bee98f5870d8ec2be4c99da52e045b44b9cef4874bc0cd7a278f4cc7d95b9121ed52f49dc8dc84

test:
  secret_key_base: a3399ed655d05c30d4e5b7e95fcce0358e07034eac19946830a6b2080fceaaf48e908d4119b765fb95b504d07428c2f898a8b8727b7a70e466f9edb71c96fcd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
